"""create core fashion tables

Revision ID: da6349c5e3de
Revises: 
Create Date: 2026-07-30 14:46:06.780165

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'da6349c5e3de'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outfits',
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('outfit_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('scenario', sa.String(length=100), nullable=False),
    sa.Column('style_tags', sa.JSON(), nullable=False),
    sa.Column('season', sa.String(length=100), nullable=True),
    sa.Column('recommendation_reason', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'outfit_id')
    )
    op.create_index('ix_outfits_user_favorite', 'outfits', ['user_id', 'is_favorite'], unique=False)
    op.create_index('ix_outfits_user_scenario', 'outfits', ['user_id', 'scenario'], unique=False)
    op.create_table('products',
    sa.Column('product_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('colors', sa.JSON(), nullable=False),
    sa.Column('sizes', sa.JSON(), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_in_stock'), 'products', ['in_stock'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_table('style_profiles',
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('preferred_styles', sa.JSON(), nullable=False),
    sa.Column('preferred_colors', sa.JSON(), nullable=False),
    sa.Column('avoided_colors', sa.JSON(), nullable=False),
    sa.Column('preferred_fits', sa.JSON(), nullable=False),
    sa.Column('avoided_materials', sa.JSON(), nullable=False),
    sa.Column('common_scenarios', sa.JSON(), nullable=False),
    sa.Column('typical_budget_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('typical_budget_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('typical_budget_min IS NULL OR typical_budget_max IS NULL OR typical_budget_min <= typical_budget_max', name='ck_style_profiles_budget_range'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('wardrobe_items',
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('wardrobe_item_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('colors', sa.JSON(), nullable=False),
    sa.Column('materials', sa.JSON(), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('style_tags', sa.JSON(), nullable=False),
    sa.Column('seasons', sa.JSON(), nullable=False),
    sa.Column('scenarios', sa.JSON(), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('available', 'laundry', 'unavailable')", name='ck_wardrobe_items_status'),
    sa.PrimaryKeyConstraint('user_id', 'wardrobe_item_id')
    )
    op.create_index('ix_wardrobe_items_user_category', 'wardrobe_items', ['user_id', 'category'], unique=False)
    op.create_index('ix_wardrobe_items_user_status', 'wardrobe_items', ['user_id', 'status'], unique=False)
    op.create_table('outfit_items',
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('outfit_id', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_reference_id', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.CheckConstraint("source = 'recommendation' OR source_reference_id IS NOT NULL", name='ck_outfit_items_source_reference'),
    sa.CheckConstraint("source IN ('wardrobe', 'product', 'recommendation')", name='ck_outfit_items_source'),
    sa.ForeignKeyConstraint(['user_id', 'outfit_id'], ['outfits.user_id', 'outfits.outfit_id'], name='fk_outfit_items_outfit', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'outfit_id', 'position')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outfit_items')
    op.drop_index('ix_wardrobe_items_user_status', table_name='wardrobe_items')
    op.drop_index('ix_wardrobe_items_user_category', table_name='wardrobe_items')
    op.drop_table('wardrobe_items')
    op.drop_table('style_profiles')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_in_stock'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_index('ix_outfits_user_scenario', table_name='outfits')
    op.drop_index('ix_outfits_user_favorite', table_name='outfits')
    op.drop_table('outfits')
    # ### end Alembic commands ###
